archivo = open(".\\archivo\\log.txt","a")
archivo.write("Nueva anetrada de registro\n")
texto = input ("Ingresa una frase: ")
edad = int(input("Ingresa tu edad:: "))
estrutura = float(input("Ingresa tu estatura: "))
archivo.write(texto)
archivo.write(f"{edad}\n")
archivo.write(str(estatura))
archivo.close()